import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Session from "@/components/AuthSession";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

import { Suspense } from "react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Session>
          <Suspense>
            {children}
            <ToastContainer />

            <link
              rel='stylesheet'
              type='text/css'
              href='https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css'
            />

            <link
              rel='stylesheet'
              type='text/css'
              href='https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css'
            />
          </Suspense>
        </Session>
      </body>
    </html>
  );
}
